sudo: required

language: python
python:
  - 3.5

services:
  - docker

env:
  global:
    - PROJECT_SANDBOX_FOLDER=/task/student

before_install:
  - ./build-container.sh base
  - ./build-container.sh multilang

script:
  - docker run -v $TRAVIS_BUILD_DIR/grading/base/inginious/:/python_lib/inginious
    -v $TRAVIS_BUILD_DIR/grading/multilang/grading/:/python_lib/grading
    -v $TRAVIS_BUILD_DIR/grading/multilang/tests/:/python_lib/tests
    ingi/inginious-c-multilang /bin/sh -c "mkdir -p $PROJECT_SANDBOX_FOLDER; export PYTHON_PATH=/python_lib:$PYTHON_PATH; cd /python_lib && pip3.5 install pytest && pytest tests"
