# DOCKER-VERSION 1.1.0

#inherit from the default container, which have all the needed script to launch tasks
FROM    ingi/inginious-c-default

# Add java 1.7
RUN     yum install -y java-1.7.0-openjdk java-1.7.0-openjdk-devel
