# DOCKER-VERSION 1.1.0

# Inherit from the base container, which have all the needed script to launch tasks
ARG   VERSION=latest
ARG	  REGISTRY
FROM  ${REGISTRY}/inginious/env-cpp:${VERSION}
LABEL org.inginious.grading.name="gcc8"
