name: Containers build and push

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch default container
        run: docker pull ingi/inginious-c-default

      - name: Install dependencies
        run: |
          sudo apt-get install python3
          python3 -m ensurepip --upgrade
          pip3 install -r requirements.txt

          #- name: Login to Docker Hub
          #uses: docker/login-action@v2
          #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push containers
        run: python3 build.py
